DapperExample/Models/Cupcake.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.DynamicData;

namespace DapperExample.Models
{
    public class Cupcake
    {
        [Key]
        public int CupcakeID { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid price")]
        public int Price { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime Created { get; set; }
                    
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime LastModified { get; set; }
    }
}

DapperExample/Models/CupcakeViewModel.cs
using Akka.Actor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DapperExample.Actors;

namespace DapperExample.Models
{
    public class CupcakeViewModel
    {
        private IActorRef target;
        private Inbox inbox;

        public CupcakeViewModel()
        {
            target = MvcApplication.ActorSystem.ActorOf(Props.Create<CupcakeActor>());
            inbox = Inbox.Create(MvcApplication.ActorSystem);
        }

        public List<Cupcake> GetCupcakes()
        {
            ActorMessage am = new ActorMessage(ActorMessageType.GetCupcakes, null);
            inbox.Send(target, am);
            var cupcakes = (List<Cupcake>)inbox.Receive(MvcApplication.Timeout);
            return cupcakes;
        }
    }
}

DapperExample/Controllers/CupcakeController.cs
using Akka.Actor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DapperExample.Actors;
using DapperExample.Models;

namespace DapperExample.Controllers
{
    public class CupcakeController : Controller
    {
        private IActorRef target;
        private Inbox inbox;

        public CupcakeController()
        {
            target = MvcApplication.ActorSystem.ActorOf(Props.Create<CupcakeActor>());
            inbox = Inbox.Create(MvcApplication.ActorSystem);
        }

        // GET: Cupcake
        public ActionResult Index()
        {
            return View();
        }

        // GET: Cupcake/Details/5
        public ActionResult Details(int id)
        {
            ViewData["id"] = id;
            return View();
        }

        // GET: Cupcake/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cupcake/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cupcake/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cupcake/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Cupcake cupcake)
        {
            try
            {
                cupcake.CupcakeID = id;
                ActorMessage am = new ActorMessage(ActorMessageType.UpdateCupcake, cupcake);
                inbox.Send(target, am);
                bool edited = (bool)inbox.Receive(MvcApplication.Timeout);
                if (edited)
                {
                    TempData["shortMessage"] = "Cupcake was successfully saved.";
                }
                else
                {
                    TempData["shortMessage"] = "Error occured while saving cupcake.";
                }
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cupcake/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cupcake/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                ActorMessage am = new ActorMessage(ActorMessageType.DeleteCupcake, id);
                inbox.Send(target, am);
                bool delete = (bool)inbox.Receive(MvcApplication.Timeout);
                if (delete)
                {
                    TempData["shortMessage"] = "Cupcake was successfully deleted.";
                }
                else
                {
                    TempData["shortMessage"] = "Error occured while deleting cupcake.";
                }
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

DapperExample/Controllers/HomeController.cs
using Akka.Actor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DapperExample.Actors;
using DapperExample.Models;

namespace DapperExample.Controllers
{
    public class HomeController : Controller
    {
        private IActorRef target;
        private Inbox inbox;

        public HomeController()
        {
            target = MvcApplication.ActorSystem.ActorOf(Props.Create<CupcakeActor>());
            inbox = Inbox.Create(MvcApplication.ActorSystem);
        }

        [HttpGet]
        public ActionResult Index()
        {
            if (TempData["shortMessage"] != null)
            {
                ViewBag.Message = TempData["shortMessage"].ToString();
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(Cupcake model)
        {
            if (ModelState.IsValid)
            {
                ActorMessage am = new ActorMessage(ActorMessageType.InsertCupcake, model);
                inbox.Send(target, am);
                bool added = (bool)inbox.Receive(MvcApplication.Timeout);
                if (added)
                {
                    ViewBag.Message = "Cupcake was successfully added.";
                }
                else
                {
                    ViewBag.Message = "Error occured while adding cupcake.";
                }
            }
            return View(model);
        }
    }
}

DapperExample/Views/Home/Index.cshtml
@using System.Web.Optimization
@using DapperExample.Models;
@model DapperExample.Models.Cupcake

@{
    ViewBag.Title = "Cupcake Shop";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm(null, null, null, FormMethod.Post, new { @class = "form-horizontal well" }))
{
    @Html.AntiForgeryToken()

    if (ViewBag.Message != null)
    {
        <div class="alert alert-success alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <strong>Ok!</strong> @ViewBag.Message
        </div>
    }

    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Please enter cupcake information.</legend>
        <div class="container">

            @Html.EditorFor(m => m.Name)
            @Html.EditorFor(m => m.Price)
            @Html.EditorFor(m => m.Created)
            @Html.EditorFor(m => m.LastModified)

        </div>
        <input class="btn btn-primary" type="submit" value="Add" />

    </fieldset>
    
    <br />

    @Html.Partial("/Views/Home/_CupcakeTable.cshtml", new CupcakeViewModel())

}

@section Scripts {
    @Scripts.Render("~/Scripts/val")
    @Scripts.Render("~/Scripts/md")
    <script>
        (function ($) {
            setTimeout(function () {
                $("div.alert").alert('close');
            }, 3000);
        })(jQuery);

    </script>
}

DapperExample/Views/Home/_CupcakeTable.cshtml
@model DapperExample.Models.CupcakeViewModel

    <table class="table table-striped">
    <tr>
        <th>
            CupcakeID
        </th>
        <th>
            Name
        </th>
        <th>
            Price
        </th>
        <th>
            Created
        </th>
        <th>
            LastModified
        </th>
        <th>
        </th>
    </tr>
    @{
        var cupcakes = Model.GetCupcakes();
        foreach (var item in cupcakes)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CupcakeID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastModified)
                </td>
                <td>
                    @Html.ActionLink("Ingredients", "Index", "Ingredient", new { id = item.CupcakeID }, null) |
                    @Html.ActionLink("Edit", "Edit", "Cupcake", new { id = item.CupcakeID }, null) |
                    @Html.ActionLink("Delete", "Delete", "Cupcake", new { id = item.CupcakeID }, null)
                </td>
            </tr>
        }
    }
</table>